name: Deploy GitHub Pages

on:
  push:
    branches:
      - main  # Adjust this to your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch submodules

      - name: Deploy to GitHub Pages
        run: |
          mkdir -p output
          cp -R starter-academic/public/* output/
          echo "ksanu1998.github.io" > output/CNAME  # Add custom domain if you have one
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add output/
          git commit -m "Deploy to GitHub Pages" || exit 0
          git push origin `HEAD:gh-pages`

